-- CONSULTA CON UNA CONDICION
SELECT * FROM usuarios WHERE email = 'correo@correo.com';

/*
OPERADORES DE COMPARACION
IGUAL =
DISTINTO !=
MENOR <
MAYOR >
MENOR O IGUAL <=
MAYOR O IGUAL >=
BETWEEN between A and B
EN = IN
NULO  = IS NULL
NO NULO = IS NOT NULL
COMO = LIKE
NO ES COMO = NOT LIKE
*/

-- EJEMPLOS

-- 1. MOSTRAR NOMBRE Y APELLIDOS DE TODOS LOS USUARIOS REGISTRADOS EN 2022
SELECT nombre, apellidos FROM usuarios WHERE YEAR(fecha_registro) = 2022;

-- 2. MOSTRAR NOMBRE Y APELLIDOS DE TODOS LOS USUARIOS  QUE NO SE REGISTRARON EN 2022
SELECT nombre, apellidos FROM usuarios WHERE YEAR(fecha_registro) != 2022;